### PR TITLE
Keep active group when using Goto commands

### LINKED ISSUE #1990: Goto definition in the same file should stay in the same tab
With more than one instance of the same file open, e.g. in 2 columns mode, goto definition always jumps to the first file instance instead of the currently focused file instance.

**To Reproduce**
1. Open 2 columns to view the same file
2. Go to the right one, goto definition on something
3. Focus jumps to the left file instance

**Expected behavior**
Focus stays on the right instance

**Environment (please complete the following information):**
- OS: macOS
- Sublime Text version: 4126
- LSP version: 1.16.3
- Language servers used: LSP-typescript

"Find references" opens a pane whose links always jump to the currently focused file instance, so I thought goto definition doing the same would be consistent.

### PR DESCRIPTION
**Pull request by jwortmann**
Fixes #1990

More general, this also aligns the behavior of LSP Goto commands with the behavior of the native commands in the following, related case: if the location is in another file, which is already opened in another group, then the LSP commands would focus the already opened tab. After this PR, it will instead create a new view for the file in the active group.

There was a logic bug in the open_file function, which caused the current behavior (assuming that the `group = -1` argument should have the same meaning as in all the Sublime API functions).

### CODE REVIEW

**Comment by jwortmann** [comment]
Well, I see now that this behavior was changed some time ago, as a result of the issue/question #886.

So the question is, do we want to use the same behavior as native ST commands do (i.e. *with* the FORCE_GROUP flag - which *is* documented now btw, and seems to be used intentionally in Default/symbol.py), or should files be focused even if they are in different groups. Apparently, there will be issues reported from users in any of the cases, because some prefer it the one or the other way...

But I guess if the "LSP Goto..." commands are meant to be a possible replacement for the native commands, then it is probably better to follow the behavior of native ST?

**Review by rwols — APPROVED** [review]
lgtm, please fix the merge conflicts

**Comment by jyounce-aim** [comment]
Hi guys, I recently upgraded to LSP v1.17.0.

My question is, how do I get this functionality back? https://github.com/sublimelsp/LSP/issues/886

I want to be able to `go to definition` and it open up in an existing open file regardless of what pane the file is in, how it used to be before this package upgrade.

Thank you,

Judd

**Comment by rchl** [comment]
If you'll look at the changes here you'll notice that the keybindings got a new argument `force_group` that defaults to `true`. I think that defining your own keybinding with value `false` should do the trick.

**Comment by jwortmann** [comment]
If you use a key binding for it, see the example but use `"force_group": false`

https://github.com/sublimelsp/LSP/blob/4b0d5fd214234013cd2055ac799b6212af1cd4b5/Default.sublime-keymap#L171-L193

For the right-click context menu you could create a new entry for it in a `Packages/User/Context.sublime-menu` file with content
```json
[
    {
        "caption": "LSP Goto Definition",
        "command": "lsp_symbol_definition",
        "args": {"force_group": false}
    },
]
```

If you use the link from the hover popup, then it is not easily possible. But I would say that LSP should follow ST's behavior, which has been like this for quite some time, and it seems to be intentional this way in ST. There is some discussion about it in https://github.com/sublimehq/sublime_text/issues/813 and in case it gets changed in the future or a setting will be introduced for it, then I guess LSP can quickly adopt that.

**Comment by maegul** [comment]
Hmmm ... changing to `"force_group": false` as @jwortmann and @rchl suggest works well ... 

... except for when there are multiple definitions of the same function/symbol and a quick panel arises.  This is quite common if you're using `overloads` in python for instance.  It's not clear to me whether this is a bug or another setting I can manipulate.

**Comment by jwortmann** [comment]
> ... except for when there are multiple definitions of the same function/symbol and a quick panel arises.

Looks like the "force_group" argument is not passed at
https://github.com/sublimelsp/LSP/blob/87e072cd2e9cb36888b99d1b07fdd3970eb408ca/plugin/goto.py#L76
and it needs to be added as another argument for the LocationPicker.

**Comment by rchl** [comment]
Addressing in https://github.com/sublimelsp/LSP/pull/2134

**Pull request merged**
