### PR TITLE
report didChangeWatchedFiles capability in a correct place

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Review by predragnikolic — APPROVED** [review]

**Review by rwols — APPROVED** [review]
d'oh! Something similar is probably wrong with client-initiated progress somewhere. I should look into that...

**Comment by rchl** [comment]
That one seems to match the spec, if that is what you mean:

Screenshot 2021-11-06 at 20 05 53

**Comment by rchl** [comment]
And for the client initiated there isn't a client capability.

**Comment by rwols** [comment]
That's **server-initiated** progress you're quoting

**Comment by rwols** [comment]
for client-initiated progress we're sending a token along with each request, and pyright is supposed to use that token, but it starts using server-initiated progress anyway for textDocument/references. It should use the provided client token but it doesn't for some reason.

**Comment by rchl** [comment]
I believe I found the issue in pyright https://github.com/microsoft/pyright/issues/2545

**Pull request merged**
