### PR TITLE
improve heuristic for picking what to show as completion trigger

### LINKED ISSUE #2189: Improve heuristic related to showing completion labels
**Describe the bug**

`typescript-language-server` will soon introduce `filterText` property which will make ST presentation of completions worse. See https://github.com/typescript-language-server/typescript-language-server/pull/678#pullrequestreview-1284240548

The change will be spec compliant and might improve things for other editors but it's not gonna work great for us so we need to improve our heuristic.

This issue also already manifests with Volar, for example. See:

Screenshot 2023-02-07 at 13 57 11

### PR DESCRIPTION
**Pull request by rchl**
See the issue for more info.

I'm not saying that this is the best or even correct solution but it's to kick-start the discussion.

Fixes #2189

### CODE REVIEW

**Comment by predragnikolic** [comment]
```diff
+   trigger = lsp_label
+   annotation = lsp_detail
    if lsp_label_detail:
        trigger = lsp_label + lsp_label_detail
        annotation = lsp_label_description or lsp_detail
-    elif lsp_label.startswith(lsp_filter_text):
-        trigger = lsp_label
-        annotation = lsp_detail
-        if lsp_label_detail:
-            details.append(html.escape(lsp_label + lsp_label_detail))
-        if lsp_label_description:
-            details.append(html.escape(lsp_label_description))
-    else:
-        trigger = lsp_filter_text
-        annotation = lsp_detail
-        details.append(html.escape(lsp_label + lsp_label_detail))
-        if lsp_label_description:
-            details.append(html.escape(lsp_label_description))
```

The spec is clear for the label(trigger) part, 
we should show the `CompletionItem.label` or the `CompletionItem.label` + `CompletionItem.labelDetails` if `labelDetails` is present in the autocomplte popup.

Id doesn't feel right to show `filterText` as the `label` in the autocomplete popup(because that value is not meant that, and I am not sure why it this line  `trigger = lsp_filter_text` was added... there was probably a reason but I forgot it).

My ideal case would be to remove the elif and else branches completely if we can.

**Comment by rchl** [comment]
The spec is written with assumption that the client can show one thing (`label`) and filter on another thing (`filterText`). ST can only filter on what it is visible so that's why we need those heuristics. Those heuristics were introduced in #2010 so you can check it for more info.

**Comment by rchl** [comment]
Added also some tests so that it's easier to reason about any changes.

**Comment by rchl** [comment]
@predragnikolic With your suggested change there is one silly test that fails:

```py
    def test_filter_text_4(self) -> None:
        # See the `test_filter_text_is_not_a_prefix_of_label` test above and
        # also https://github.com/sublimelsp/LSP/issues/771
        # This is probably a silly server behavior that we probably shouldn't need to support?
        self._verify_completion(
            {
                "label": "Implement all members",
                "filterText": "e",
            },
            trigger='e',
        )
```

But honestly it is quite weird server behavior and it might even have been addressed in the server already (maybe).

No other tests that I've added seem to fail which is quite surprising to me and means that either we are missing some relevant tests or it could actually work.

**Comment by predragnikolic** [comment]
Currently reading this https://github.com/sublimelsp/LSP/pull/990  🙂

I will study all the changes and hopefully I will have a conclusion tomorrow.

**Comment by predragnikolic** [comment]
filterText was used in the era when lsp_label_details didn't exist, 
to better format things with in the autocomplete popup.

currently, when we have dedicated fields in the spec, label detail and description, the workaround with the filterText is no longer necessary. It made sense then, but not now.

The more I read it the more I believe that we will be able to delete the elif, else branches 🙂

Also if you have time, do a quick look of what other servers return for the filterText, some return just a char, which IMO would be pretty bad to show in the AC popup (but that case didn't happen with servers that I use, and nobody reported such issues)... 
But the reason why we have this PR in the first place is because we have a bug because we are using filterText as a label. 

If you(or somebody) still have some case why filterText should be used, please say. Otherwise I am 100% for removing it.

**Comment by jwortmann** [comment]
I think this change doesn't make sense, for the reasons explained in https://github.com/sublimelsp/LSP/issues/2189#issuecomment-1426199595. We should use `filterText` for the trigger (unless no information is lost if using the `label` instead). And we have to live with the downside that it doesn't look very nice in some special occasions, because ST just doesn't have the ability to match against something different to what is shown in the trigger.

**Comment by rchl** [comment]
Closing based on discussions here and in the issue.

I will till get the tests in separately.

**Pull request closed without merging**
