### PR TITLE
Add LSP: Troubleshoot Server to Command Palette

### PR DESCRIPTION
**Pull request by rchl**
Opens a sheet with all information that should be necessary to diagnose
problems with a server. Important part of that is that it runs selected
server to catch and show its stderr output. Something that is a pain to
do manually.

### CODE REVIEW

**Comment by rchl** [comment]
Not sure how to fix this:
```
plugin/tooling.py:214: error: Signature of "run" incompatible with supertype "ApplicationCommand"
```
so that both:
```
    def run(self, contents: str) -> None:
```
and
```
    def run(self) -> None:
```

Tried using **kwargs and *args but nothing seems to work.

**Comment by rchl** [comment]
There is something going wrong with code highlighting and mdpopups. Need to investigate that.

**Comment by rwols** [comment]
This is pretty cool. Perhaps we can add another command that dumps the server's capabilities (in another PR).

**Comment by rchl** [comment]
> This is pretty cool. Perhaps we can add another command that dumps the server's capabilities (in another PR).

Hmm, maybe, but not sure.

I've tried to not go deeper with interacting with the server than just starting it. Having to exchange messages would be on slightly deeper level.

Also, that information is already possible to get by enabling normal logging. The point of starting the server in this change is to mainly catch the server's output on server failing to start, something that is completely lost in normal situations because we capture stderr but never show it to the user. That's why user's had to start servers manually from the terminal to debug those issues before.

**Pull request merged**
