### PR TITLE
Mention experimental multi module gopls option

### LINKED ISSUE #1471: Hint about gopls multi-module workspace support
**Describe the bug**
Not really a bug but a hint for other go users.

**To Reproduce**
1. have a single git repo with many go modules.
2. try to use lsp features like goto definition.
3. fail with errors like `no object found for ident X`

**Expected behavior**
LSP features to work.

**Additional context**
In gopls [v0.5.3](https://github.com/golang/tools/releases/tag/gopls%2Fv0.5.3) an experimental mode for multi modules was added. I enabled it in my sublime lsp config like this:

```json
"gopls":
	{
		"enabled": true,
		"initializationOptions": {
			"experimentalWorkspaceModule": true
		}
	},
```
Then goto definition etc works as expected.

### PR DESCRIPTION
**Pull request by ottob**
Fixes #1471

### CODE REVIEW

**Comment by ottob** [comment]
@predragnikolic feel free to copy this change into #1490 and close this one.

**Comment by predragnikolic** [comment]
LGTM, 

But @ottob If you want you change to appear on https://lsp.readthedocs.io/en/latest/ (the current documentation)
You would have to fork the master branch(instead of the st4000-exploration)
and create a PR to the master branch (instead of the st4000-exploration) :) 

Right now if we were to merge it to the st4000-exploration,
it won't appear on https://lsp.readthedocs.io/en/latest/
but rather https://sublimelsp.github.io/LSP/ (which is currently under construction, and not yet meant for public).

**Comment by ottob** [comment]
I think its fine if it goes to the `st4000-exploration` branch. It doesn't seem to be a very common issue. And people will probably find it here if they search for it.

**Comment by predragnikolic** [comment]
Are you sure that this goes to `initializationOptions`
```
"gopls": {
  "enabled": true,
  "initializationOptions": {
    "experimentalWorkspaceModule": true
  }
}
```
and not to `settings`
```
"gopls": {
  "enabled": true,
  "settings": {
    "gopls": {
      "experimentalWorkspaceModule": true
    }
  }
}
```
This is what I have read in the release notes you posted:

https://github.com/golang/tools/releases/tag/gopls%2Fv0.5.3
> Enable multi-module workspace support by adding the following to your settings:
```
"gopls": {
    "experimentalWorkspaceModule": true,
}
```

Can you confirm that setting `experimentalWorkspaceModule` in `initializationOptions` works? :)

**Comment by ottob** [comment]
Yes, setting it as an `initializationOptions` was the only thing that worked for me.

**Comment by ottob** [comment]
Actually both ways of setting it seems to work.

**Comment by predragnikolic** [comment]
Thanks for checking :) 
I will leave it in the initialization options.

**Comment by predragnikolic** [comment]
image

added with https://github.com/sublimelsp/LSP/pull/1490/commits/f7fb37ebf3f460a45c1c2d84a023b2c39a1ea435 (I slightly changed the text)

Is it ok?

**Comment by predragnikolic** [comment]
closed with https://github.com/sublimelsp/LSP/pull/1490

**Comment by predragnikolic** [comment]
Thanks for the effort!

**Pull request closed without merging**
