### PR TITLE
Pass force_group to LocationPicker

### PR DESCRIPTION
**Pull request by rchl**
Addressing issue mentioned in https://github.com/sublimelsp/LSP/pull/1994#issuecomment-1270279134

### CODE REVIEW

**Comment by jwortmann** [comment]
Judging from the diff here, the argument is still not passed from the "Goto ..." commands. So I guess at the current state it wouldn't solve the linked issue, and still just use the default value `True` ...

**Comment by rchl** [comment]
I admit I haven't bothered to test the original issue but I've assumed that this is fixing the case when somewhere has defined a custom command that passes "force_group: false". Is that not the case?

**Comment by rchl** [comment]
I see now. Forgot to change the place that you've actually indicated is the issue.

That said, still haven't tested as pyright doesn't trigger this code path and I didn't bother to find out how to trigger it.

**Comment by rchl** [comment]
Looks better now @jwortmann ?

**Comment by jwortmann** [comment]
Yes, should be fine to merge now.

It was obvious to me that you had just forgotten to adjust the other place in the code. Maybe I should have expressed that more clearly ;-)

**Pull request merged**
