### PR TITLE
Remove registration of the legacy LanguageHandler class

### PR DESCRIPTION
**Pull request by rwols**
I can't find any package any more that still uses this.

### CODE REVIEW

**Comment by predragnikolic** [comment]
I guess only these 2 plugins that are published on PC still use LanguageHandler:

https://github.com/prometheus-community/sublimelsp-promql/blob/master/plugin.py#L130 (not part of the LSPSublimeOrg)
https://github.com/sublimelsp/LSP-Serenata/blob/master/plugin.py#L10

**Comment by predragnikolic** [comment]
Will you also delete the `/LSP/plugin/core/handlers.py` file?

**Comment by jfcherng** [comment]
> I guess only these 2 plugins that are published on PC still use LanguageHandler:
> 
> [prometheus-community/sublimelsp-promql@`master`/plugin.py#L130](https://github.com/prometheus-community/sublimelsp-promql/blob/master/plugin.py?rgh-link-date=2022-01-19T13%3A40%3A49Z#L130) (not part of the LSPSublimeOrg) [sublimelsp/LSP-Serenata@`master`/plugin.py#L10](https://github.com/sublimelsp/LSP-Serenata/blob/master/plugin.py?rgh-link-date=2022-01-19T13%3A40%3A49Z#L10)

LSP-Serenata hasn't updated for 2 years and the server, [Serenata](https://gitlab.com/Serenata/Serenata) was last active commit in 10 months ago. Consider PHP is evolving every year, I may assume both of LSP-Serenata and Serenata are gradually outdated...

**Review by rchl — APPROVED** [review]
In `boot.py` those are unused:

- import weakref
- `Callable` and `Tuple` from `.plugin.core.typing`

Also maybe we should be defining `__all__` to clearly indicate which imports are "public". That would also get rid of all false positive warnings that import is "unused".

**Pull request merged**
