### PR TITLE
Catch crash on trying to update diagnostics in file that doesn't exist

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by jwortmann** [comment]
Right, I had not thought of this. Looks good to me.

**Comment by rwols** [comment]
I thought this was merged into master but it merged into st4000-exploration. Shouldn't this be in master?

**Comment by rchl** [comment]
Yes, I suppose we should cherry pick there.

**Comment by rwols** [comment]
https://github.com/sublimelsp/LSP/commit/19fa94dcf1c20fea071baaf2df725d4d2102a41e

**Pull request merged**
