### PR TITLE
Rename LspTextCommand.session -> LspTextCommand.best_session

### PR DESCRIPTION
**Pull request by rwols**
Done with pyls' now correctly working textDocument/rename, pretty nice.

All tests pass and tox doesn't complain, so I'm assuming everything went well.

### CODE REVIEW

**Comment by rchl** [comment]
Love the idea of not using generic "session" name for a method.

Can we also rename `LSPViewEventListener.session`?

**Comment by rchl** [comment]
Maybe consider keeping the old method name as an alias for a few releases (with a deprecation message)?

**Comment by rwols** [comment]
> Maybe consider keeping the old method name as an alias for few releases (with a deprecation message)?

For who? Nobody said you could use `LspTextCommand` :)

**Comment by rchl** [comment]
> For who? Nobody said you could use `LspTextCommand` :)

But that doesn't mean that nobody did. :)
But maybe better to just visibly break those cases.

**Pull request merged**
