### PR TITLE
Docs organise navigation

### PR DESCRIPTION
**Pull request by predragnikolic**
This PR is about splitting up the index page where we have a lot of information,
into multiple smaller pages.  This is to make grounds for a better organized navigation.

**I haven't changed the content**, although there were some smaller changes like 86d65934d63597b41df6bd1ba47a21b3cb89e8bb.
I am planning to change the content in later PRs and each PR will be responsible for one page. To make it easier to reason about.

changed:

- turn the following navigation:

```
Home
C/C++
Features
Troubleshooting
```

to ->

```
Getting Started
Language Servers
Features
Guides >
    Server Configuration
    Setup C/C++
Troubleshooting
```

removed: 
- issue template 5a1ad3e (we don't need it)

### CODE REVIEW

**Comment by rwols** [comment]
Can you make these changes on the sublimelsp remote in some branch so I don't have to add another remote to check out these changes?

**Comment by rwols** [comment]
I did not mean merge it into st4000-exploration

**Comment by predragnikolic** [comment]
I don't know how this exactly happen but I didn't pressed merge.

**Comment by predragnikolic** [comment]
I will revert the merge.

**Comment by predragnikolic** [comment]
Sorry :)

**Comment by predragnikolic** [comment]
Well.. I made some :hankey: :( :)
Please leave a review of the changes you would want to make and I will create a follow up PR. Sorry for the inconvenience.

**Comment by rwols** [comment]
No worries.

Server configuration:

- document_selector -> selector
- feature_selector -> priority_selector
- languages: don't mention this
- languageId: don't mention this
- tcp_host: not implemented (it used to work at some point, but then didn't, then it got removed)
- tcp_mode: replaced by negative numbers for tcp_port

Have a section about language IDs and how they relate to base scopes.

**Comment by rwols** [comment]
Maybe we can generate the "server configuration" page entirely from the sublime-package.json?

**Pull request merged**
