### PR TITLE
Fix formatting and numbering for items

### PR DESCRIPTION
**Pull request by jfacorro**
It was pointed out [here](https://github.com/sublimelsp/LSP/pull/916#issuecomment-602043968) that after having deleted trailing whitespaces which signaled newlines, the format of the Julia and Fortran sections was broken. Also the numbering in the Erlang section was off.

This PR removes the reliance on trailing whitespaces and fixes the numbering.

### CODE REVIEW

**Comment by rwols** [comment]
This removes the syntax highlighting in the code blocks. I'm okay with that. What do you think @jwortmann ?

**Comment by jfcherng** [comment]
> This removes the syntax highlighting in the code blocks.

But why we have to? `readthedocs` doesn't support it (I have never used it before)?


# Source

````
1. 1st
1. 2nd

   ```json
   "erlang-ls": {
     "test": 1
   }
   ```

1. 3rd
````


# Github Rendered

1. 1st
1. 2nd

   ```json
   "erlang-ls": {
     "test": 1
   }
   ```

1. 3rd

**Comment by jwortmann** [comment]
Readthedocs uses Mkdocs to generate the html pages from Markdown. GitHub apparently uses another Markdown engine, here is how Mkdocs renders the code from @jfcherng for me locally:
screenshot

The reason I used escaped dots `1\.` after the numbers instead of lists was that I found no other way to keep the syntax highlighting for the code blocks. Empty lines between items instead of the trailing double space will actually add empty lines in the rendered html.
  
I would at least suggest to keep the syntax highlighting for the json and js fenced code blocks after the third list item.

**Comment by jfcherng** [comment]
For mkdocs, the following is good in my test.

````
1. 1st
1. 2nd

    ```json
    "erlang-ls": {
      "test": 1
    }
    ```

1. 3rd
````

But generally I don't like dedicated tweaks if I don't know why it works.

**Comment by rwols** [comment]
Hmm, I'm not sure what to do with this PR. Personally I don't really mind the missing highlighting. If nobody speaks up I'll merge this tomorrow.

**Comment by jwortmann** [comment]
I've tested how the generated html from Mkdocs will look like, and interestingly we actually don't lose the highlighting with this change. Seems like the JSON/JavaScript language is automatically recognized for indented code blocks and there is only a different line spread. With that in mind, I'm fine with this change.

screenshot

**Pull request merged**
