### PR TITLE
More small code style improvements

### PR DESCRIPTION
**Pull request by jwortmann**
... continuing from #2537.

There should be no functional change.

### CODE REVIEW

**Review by predragnikolic — APPROVED** [review]

**Comment by rchl** [comment]
(rewrote history to merge linting fixing into respective commits)

**Review by rchl — APPROVED** [review]

**Comment by jwortmann** [comment]
> (rewrote history to merge linting fixing into respective commits)

But then you squashed it into a single commit :D

**Comment by rchl** [comment]
Yeah, my intention was to merge them as separate commits but will keep as is then.

**Comment by rchl** [comment]
BTW. You can work directly in this repo if you'd prefer that.

**Comment by jwortmann** [comment]
To be honest I kind of prefer using a personal remote repo. There are already various stale branches in this repo. But I guess it would make it easier for you to quickly checkout my branches or add changes if I would push directly to this repo... I'll think about it.

**Comment by predragnikolic** [comment]
Choosing squash was a bad decision on my part. Sorry for the inconvenience and effort that @rchl did to group commits.

**Pull request merged**
