### PR TITLE
Fix plugin overwrite `on_workspace_configuration`

### PR DESCRIPTION
**Pull request by LDAP**
Currently, plugins can not set the configuration object in `on_workspace_configuration` if it is `None` or it has to be replaced completely.

This did only work in those cases where `configuration` was a reference to an object that could be altered.

See 
https://github.com/sublimelsp/LSP-jdtls/commit/85f2392c9af3cdbf5048bdac8fad81cb29a1c95a
for an example where the current implementation does not work.

This PR changes `on_workspace_configuration` so that it must return the new configuration item. The default implementation now forwards the "pre-resolved" configuration.

### CODE REVIEW

**Comment by rchl** [comment]
It's a breaking change for LSP-eslint: https://github.com/sublimelsp/LSP-eslint/blob/fd903029a075497d6c8eeecbe980a6c4748e6ac7/plugin.py#L70-L70

Will you also create a PR that adapts it to use the changed API?

(Normally I would prefer a non-breaking change or new API but I think that we can pretty confidently say that nothing else is using this API so it should be fine.)

**Comment by LDAP** [comment]
Yes, I'll create a PR there too.

**Comment by LDAP** [comment]
I opened a PR as far as I can see we can publish the LSP-eslint change without breaking anything. The LSP must be released before LSP-jdtls.

(I tried to think of a non-breaking solution but could not come up with something better)

**Review by rchl — APPROVED** [review]

**Comment by rchl** [comment]
Released new LSP version with this fix.

**Pull request merged**
