### PR TITLE
Introduce the SessionBuffer class

### PR DESCRIPTION
**Pull request by rwols**
SessionView Part II: Attack of the Clones

This solves the clones problem by storing state per session *per buffer* instead of per session *per view*. Multiple views may refer to the same underlying buffer.

After this we can store diagnostics in the SessionBuffer class.

### CODE REVIEW

**Comment by rchl** [comment]
Looks fine apart from failing test

**Comment by rchl** [comment]
Actually seems kinda broken in regards to document syncing or something as CAOS breaks formatting on saving.

**Comment by rwols** [comment]
What is broken about it exactly? Can you point me to something reproducible? I still have nuxt-i18n checked out locally.

**Comment by rchl** [comment]
I've added one comma and `textDocument/didChange` shows this:
```json
{
  "contentChanges": [
    {
      "range": {
        "end": {
          "character": 12,
          "line": 138
        },
        "start": {
          "character": 12,
          "line": 138
        }
      },
      "rangeLength": 0,
      "text": ","
    },
    {
      "range": {
        "end": {
          "character": 12,
          "line": 138
        },
        "start": {
          "character": 12,
          "line": 138
        }
      },
      "rangeLength": 0,
      "text": ","
    },
    {
      "range": {
        "end": {
          "character": 12,
          "line": 138
        },
        "start": {
          "character": 12,
          "line": 138
        }
      },
      "rangeLength": 0,
      "text": ","
    }
  ],
  "textDocument": {
    "uri": "file:///Users/me/workspace/lsp-log-parser/components/log-view.vue",
    "version": 1
  }
}
```

**Comment by rchl** [comment]
BTW. I have 3 sessions running on this file which is probably worth mentioning.

**Pull request merged**
