### PR TITLE
Remove mutex from promise

### PR DESCRIPTION
**Pull request by rwols**
Completions are janky now. Removing the mutex from the promise solves this.

### CODE REVIEW

**Comment by rchl** [comment]
Is it safe though?

And if it's safe is it only because of how it is used right now (only from a single thread)? And if so, would it be likely that we would introduce a case in the future where it's not safe?

Also, i haven't noticed completions being janky. Are you able to show the issue on video or something?

**Comment by rchl** [comment]
Actually if it would only be used from a single thread then you should not be able to notice any jank since the threads would not be blocking. So it's it safe then?

**Comment by predragnikolic** [comment]
I also haven't noticed completions being janky

**Comment by rwols** [comment]
I can't seem to reproduce it now...

**Pull request closed without merging**
