### PR TITLE
Tests: start and stop session at the TestCase level

### PR DESCRIPTION
**Pull request by rwols**
The tests run in turbo mode now :) It takes about ~17 seconds to run the ~200 tests. Old time is about ~32 seconds here.

I also removed the `ensure_document_listener_created` method. I don't think this is necessary anymore.

### CODE REVIEW

**Comment by rchl** [comment]
Nice!

Got some error but it didn't affect testing:
```
Traceback (most recent call last):
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/documents.py", line 358, in <lambda>
    sublime.set_timeout_async(lambda: self._on_query_completions_async(promise, locations[0]))
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/documents.py", line 529, in _on_query_completions_async
    self.purge_changes_async()
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/documents.py", line 617, in purge_changes_async
    sv.purge_changes_async()
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/session_view.py", line 158, in purge_changes_async
    self.session_buffer.purge_changes_async(self.view)
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/session_buffer.py", line 207, in purge_changes_async
    notification = did_change(view, c)
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/core/views.py", line 271, in did_change
    return Notification.didChange(did_change_text_document_params(view, changes))
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/core/views.py", line 237, in did_change_text_document_params
    result = {"textDocument": versioned_text_document_identifier(view), "contentChanges": content_changes}
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/core/views.py", line 212, in versioned_text_document_identifier
    return {"uri": uri_from_view(view), "version": view.change_count()}
  File "/Users/me/workspace/lsp/Sublime LSP.app/Contents/MacOS/Data/Packages/LSP/plugin/core/views.py", line 179, in uri_from_view
    raise MissingFilenameError(view.id())
LSP.plugin.core.views.MissingFilenameError: View 119 has no filename
```

**Comment by rchl** [comment]
> I also removed the `ensure_document_listener_created` method. I don't think this is necessary anymore.

This was necessary for CI and looks like it would still be needed if we'd run tests on CI.
The issue shows up when the ST window is not active and you can still reproduce it if you unfocus the window after starting testing.

**Comment by rwols** [comment]
Wasn't it fixed with this diff?

https://github.com/SublimeText/UnitTesting/pull/181

**Comment by rchl** [comment]
I'm not sure now if it reliably fixed CI. CI might be losing focus for different reasons also.

But in any case, this is also a problem locally when just unfocusing ST window during testing which sometimes can happen accidentally and sometimes it happens on purpose. It would be a shame to get more reasons for unpredictable behavior due to removing this workaround.

**Review by rchl — APPROVED** [review]

**Pull request merged**
