### PR TITLE
Document LSP-tailwindcss

### PR DESCRIPTION
**Pull request by predragnikolic**

### CODE REVIEW

**Comment by rwols** [comment]
What's up with the CI?

**Comment by predragnikolic** [comment]
```
name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"  <<<< Maybe because of this?
```

**Review by rwols — APPROVED** [review]

**Comment by rwols** [comment]
We should probably link to packagecontrol.io pages instead, as not everyone may use GitHub.

**Comment by predragnikolic** [comment]
True.

**Pull request merged**
