### PR TITLE
Make symbol highlight faster by reducing the debounce time

### PR DESCRIPTION
**Pull request by predragnikolic**
This makes the highlights show up a lot faster. (I haven't noticed any perf issue with this, but I like how much the highlight feels faster)

### CODE REVIEW

**Comment by rchl** [comment]
The debounce time is a compromise between being too slow and too noisy. I'm not sure if 150ms is a better option. It will make it noisier when navigating the code. For example here I navigate between lines fairly fast and it still triggers:
highlight

Maybe we could get it down to 350ms for example?

**Comment by rwols** [comment]
I am worried that this might indeed be too quick.

**Comment by predragnikolic** [comment]
> 350ms

I bumped it to 300ms. Is it sufficient?

**Comment by rchl** [comment]
I'm fine with that.

**Review by rchl — APPROVED** [review]

**Pull request merged**
