### PR TITLE
use DRAW_EMPTY_AS_OVERWRITE for empty regions

### PR DESCRIPTION
**Pull request by predragnikolic**
This is a follow up PR, based on feedback:
https://github.com/sublimelsp/LSP/pull/1371#discussion_r502964924

Current behavior (that was added with #1371):
image

DRAW_EMPTY_AS_OVERWRITE:
Screenshot from 2020-10-12 19-37-59

DRAW_EMPTY:
Screenshot from 2020-10-12 19-37-03

---
I think the current behavior is ok, but I think that DRAW_EMPTY_AS_OVERWRITE is also ok.
I wouldn't go with DRAW_EMPTY because it is a vertical line.

The only disadvantage about the DRAW_EMPTY_AS_OVERWRITE is that the line in not squiggly, or a box, or whatever the user set in the LSP.sublime-settings file.
Someone could open an issue telling us that they set `"diagnostics_highlight_style": "box",` 
but they still see a line:
- notice the first line - **box**, 
- notice the line bellow `import Url exposing (Url`  - **line**
image
 

Feel free to close this PR if you think that the current behavior is ok,
or feel free to merge this if you think that the behavior of DRAW_EMPTY_AS_OVERWRITE is ok.

### CODE REVIEW

**Comment by rwols** [comment]
But are these empty regions now hoverable with the mouse?

**Comment by predragnikolic** [comment]
Yes, they are.

**Comment by predragnikolic** [comment]
I don't know if people would be confused by the look of DRAW_EMPTY_AS_OVERWRITE:
https://github.com/sublimelsp/LSP/issues/858#issuecomment-577271147

To be honest I would expect to see a squiggle underline| box 
instead of a straight line.

**Comment by rchl** [comment]
I might be leaning towards `DRAW_EMPTY` actually since the region is actually empty so the vertical line seems more appropriate. And also it eliminates the problem of underline being displayed differently from user preference.

**Comment by rwols** [comment]
I would also prefer `DRAW_EMPTY` :)

**Comment by predragnikolic** [comment]
To me it all comes down weather we want to display diagnostics consistently or not :)

not so consistent: (DRAW_EMPTY)
image


consistent: (Current behavior)
image

Except for that I have no other arguments against `DRAW_EMPTY`.

**Review by rwols — APPROVED** [review]

**Comment by rchl** [comment]
It's not perfect either way since with DRAW_EMPTY the style is not consistent but with the current approach the range is not really accurate since it's expanded to the next character.

**Comment by rchl** [comment]
Hmm, after working with it for a while, I find it a bit confusing that it looks almost exactly like the "or" operator:

Screenshot 2020-10-18 at 20 46 38

(The one at the end is an error)

**Comment by predragnikolic** [comment]
Feel free to revert this PR 🙂

**Comment by rwols** [comment]
This PR does the right thing, because if you start changing regions of length zero into regions of length one, then you cannot distinguish between actual regions of length one, and regions of length zero (to put it in mathematical terms, the mapping is no longer injective :) )

So the only thing we can debate is the presentation/rendering of these zero-length regions.

**Pull request merged**
