### PR TITLE
Reply to all requests

### PR DESCRIPTION
**Pull request by rwols**
- When there's no request handler, reply with an error with code MethodNotFound
- When there's an exception thrown in the request handler, translate that exception to an error response.
- When there's an exception of type Error thrown in the request handler, send that error as-is.

Quoting the JSON-RPC 2.0 spec, which LSP is based on:

    When a rpc call is made, the Server MUST reply with a Response,
    except for in the case of Notifications.

Admittedly this is talking about "the server", but the LSP spec page says every request must be paired with a response, omitting the word "server": https://microsoft.github.io/language-server-protocol/specification#requestMessage

And the wikipedia page also talks about "the receiver" of a request: https://en.wikipedia.org/wiki/JSON-RPC#Usage

In any case, this creates two unhandled exceptions in eslint:

```
lsp-eslint: ESLint server running in node v12.13.1
lsp-eslint: Registering request handler for workspace/didChangeConfiguration failed.
lsp-eslint: (node:20544) UnhandledPromiseRejectionWarning: Error: client/registerCapability
lsp-eslint: at handleResponse (/home/raoul/.config/sublime-text-3/Packages/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:447:48)
lsp-eslint: Registering request handler for workspace/didChangeWorkspaceFolders failed.
lsp-eslint: at processMessageQueue (/home/raoul/.config/sublime-text-3/Packages/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:274:17)
lsp-eslint: at Immediate.<anonymous> (/home/raoul/.config/sublime-text-3/Packages/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:258:13)
lsp-eslint: at processImmediate (internal/timers.js:439:21)
lsp-eslint: (node:20544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
lsp-eslint: (node:20544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lsp-eslint: (node:20544) UnhandledPromiseRejectionWarning: Error: client/registerCapability
lsp-eslint: at handleResponse (/home/raoul/.config/sublime-text-3/Packages/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:447:48)
lsp-eslint: at processMessageQueue (/home/raoul/.config/sublime-text-3/Packages/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:274:17)
lsp-eslint: at Immediate.<anonymous> (/home/raoul/.config/sublime-text-3/Packages/LSP-eslint/vscode-eslint/node_modules/vscode-jsonrpc/lib/main.js:258:13)
lsp-eslint: at processImmediate (internal/timers.js:439:21)
lsp-eslint: (node:20544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
lsp-eslint: ESLint library loaded from: /home/raoul/Documents/Programming/temp/nuxt-i18n/node_modules/eslint/lib/api.js
:: --> lsp-eslint initialize(1): {'rootPath': '/home/raoul/Documents/Programming/temp/nuxt-i18n', 'capabilities': {'workspace': {'executeCommand': {}, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'didChangeConfiguration': {}, 'workspaceFolders': True, 'applyEdit': True, 'configuration': True}, 'textDocument': {'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'formatting': {}, 'declaration': {'linkSupport': True}, 'definition': {'linkSupport': True}, 'colorProvider': {}, 'references': {}, 'synchronization': {'willSaveWaitUntil': True, 'didSave': True, 'willSave': True}, 'rangeFormatting': {}, 'implementation': {'linkSupport': True}, 'signatureHelp': {'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'publishDiagnostics': {'relatedInformation': True}, 'rename': {}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'documentHighlight': {}, 'typeDefinition': {'linkSupport': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}}}, 'processId': 20503, 'workspaceFolders': [{'name': 'nuxt-i18n', 'uri': 'file:///home/raoul/Documents/Programming/temp/nuxt-i18n'}], 'rootUri': 'file:///home/raoul/Documents/Programming/temp/nuxt-i18n'}
:: --> javascript-typescript-langserver initialize(1): {'rootPath': '/home/raoul/Documents/Programming/temp/nuxt-i18n', 'capabilities': {'workspace': {'executeCommand': {}, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'didChangeConfiguration': {}, 'workspaceFolders': True, 'applyEdit': True, 'configuration': True}, 'textDocument': {'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'formatting': {}, 'declaration': {'linkSupport': True}, 'definition': {'linkSupport': True}, 'colorProvider': {}, 'references': {}, 'synchronization': {'willSaveWaitUntil': True, 'didSave': True, 'willSave': True}, 'rangeFormatting': {}, 'implementation': {'linkSupport': True}, 'signatureHelp': {'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'publishDiagnostics': {'relatedInformation': True}, 'rename': {}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'documentHighlight': {}, 'typeDefinition': {'linkSupport': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}}}, 'processId': 20503, 'workspaceFolders': [{'name': 'nuxt-i18n', 'uri': 'file:///home/raoul/Documents/Programming/temp/nuxt-i18n'}], 'rootUri': 'file:///home/raoul/Documents/Programming/temp/nuxt-i18n'}
:: <<< lsp-eslint 1: {'capabilities': {'textDocumentSync': {'openClose': True, 'save': {'includeText': False}, 'change': 1, 'willSaveWaitUntil': True}, 'codeActionProvider': True, 'executeCommandProvider': {'commands': ['eslint.applySingleFix', 'eslint.applySameFixes', 'eslint.applyAllFixes', 'eslint.applyAutoFix', 'eslint.applyDisableLine', 'eslint.applyDisableFile', 'eslint.openRuleDoc']}}}
::  -> lsp-eslint workspace/didChangeConfiguration: {'settings': {'run': 'onType', 'options': {}, 'quiet': False, 'workspaceFolder': None, 'autoFix': True, 'packageManager': 'npm', 'autoFixOnSave': True, 'nodePath': None, 'validate': True, 'codeAction': {'showDocumentation': {'enable': True}, 'disableRuleComment': {'location': 'separateLine', 'enable': True}}}}
::  -> lsp-eslint initialized: {}
::  -> lsp-eslint textDocument/didOpen
:: <-- lsp-eslint client/registerCapability(0): {'registrations': [{'registerOptions': {}, 'method': 'workspace/didChangeConfiguration', 'id': '26587724-6caa-4847-b929-ba795ecc773f'}]}
:: ~~> lsp-eslint 0: {'code': -32601, 'message': 'client/registerCapability'}
:: <-- lsp-eslint client/registerCapability(1): {'registrations': [{'registerOptions': {}, 'method': 'workspace/didChangeWorkspaceFolders', 'id': '87d6f0f6-5264-445a-9010-00d39a6478b0'}]}
:: ~~> lsp-eslint 1: {'code': -32601, 'message': 'client/registerCapability'}
```

(Error responses are prefixed with `~~>` and `<~~`)

However eslint seems to be tugging along just fine.

Screenshot from 2020-03-14 13-51-38

### CODE REVIEW

**Comment by rchl** [comment]
As the message say `Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process`, so it's not good as it can start crashing hard in the future but I can try to upstream a fix to eslint server where it will handle that rejected promise (and do nothing most likely).

**Comment by jwortmann** [comment]
I've tested this and can confirm that the Julia server v2.0.0 is working again with the current master branch. Thanks @rwols !

**Comment by rwols** [comment]
Does julia 2.0 also require this PR? I was under the impression that it didn't, but if so, I can push a new release to package control. I decided to not include this in 0.9.6 because it feels like a rather big change.

**Comment by jwortmann** [comment]
Yes, the change from this PR is required too. With the current version 0.9.6 from Package Control the server does not respond after the unhandled `client/registerCapability` message.

**Comment by rwols** [comment]
I've pushed a new patch release, 0.9.7, with this fix included.

**Comment by rwols** [comment]
The Julia LS advertises that it supports workspaces: https://github.com/julia-vscode/LanguageServer.jl/blob/4b53627bf45da8b25e29880cb43c0171d17d8741/src/requests/init.jl#L31

That means that we notify workspace/didChangeWorkspaceFolders notifications.

But then Julia LS sends a client/registerCapability with workspace/didChangeWorkspaceFolders: https://github.com/julia-vscode/LanguageServer.jl/blob/4b53627bf45da8b25e29880cb43c0171d17d8741/src/requests/init.jl#L161

This is redundant according to spec: text editors should notify workspace/didChangeWorkspaceFolders when the server has capability `workspace.workspaceFolders.supported`.

I've stumbled on this "problem" earlier in https://github.com/sublimelsp/LSP/pull/911#issuecomment-599510230.

**Pull request merged**
